- name: "data_mock_multi_build"
  args:
    n_samples: 1000
    n_vars: 5
    null_seed: 50
    date_index: True
    uniform: True
  function: 
    - "2*x1+4*x3-x2+x4*np.sin(x2*x1)"
    - "x1 + x0"
  path: "/home/azureuser/mockingjay/data"
- name: "data_mock_multi_predict"
  args:
    n_samples: 200
    n_vars: 5
    null_seed: 15
    date_index: True
    uniform: True
  function: 
    - "2*x1+4*x3-x2+x4*np.sin(x2*x1)"
    - "x1 + x0"
  path: "/home/azureuser/mockingjay/data"